# Generated by Django 5.1 on 2024-09-09 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carprofilemodel',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_profile', to='cars.carmodel'),
        ),
    ]
