# Generated by Django 5.1 on 2024-09-10 09:01

from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carprofilemodel_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='carprofilemodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.services.file_service.FileService.upload_car_photo),
        ),
    ]
