# Generated by Django 5.1 on 2024-09-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carprofilemodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carprofilemodel',
            name='region',
            field=models.CharField(choices=[('Volyn', 'Volyn'), ('Lviv', 'Lviv'), ('Zakarpattia', 'Zakarpattia'), ('Rivne', 'Rivne'), ('Ternopil', 'Ternopil'), ('Ivano-Frankivsk', 'Ivano-Frankivsk'), ('Khmelnytskyi', 'Khmelnytskyi'), ('Chernivtsi', 'Chernivtsi'), ('Zhytomyr', 'Zhytomyr'), ('Vinnytsia', 'Vinnytsia'), ('Kyiv', 'Kyiv'), ('Cherkasy', 'Cherkasy'), ('Kirovohrad', 'Kirovohrad'), ('Odesa', 'Odesa'), ('Mykolaiv', 'Mykolaiv'), ('Chernihiv', 'Chernihiv'), ('Poltava', 'Poltava'), ('Dnipropetrovsk', 'Dnipropetrovsk'), ('Kherson', 'Kherson'), ('Zaporizhzhia', 'Zaporizhzhia'), ('Sumy', 'Sumy'), ('Kharkiv', 'Kharkiv'), ('Donetsk', 'Donetsk'), ('Luhansk', 'Luhansk'), ('Krym', 'Krym')], max_length=16),
        ),
    ]
