# Generated by Django 5.1.1 on 2024-09-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_viewmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True)),
                ('byu', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('sell', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'currencies',
                'ordering': ('id',),
            },
        ),
    ]
