# Generated by Django 5.1 on 2024-09-10 00:10

from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profilemodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.services.file_service.FileService.upload_user_photo),
        ),
    ]
