# Generated by Django 5.1.1 on 2024-09-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_usermodel_photo_profilemodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='photo',
        ),
    ]
