# Generated by Django 5.1 on 2024-09-09 10:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'brands',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(100000000)])),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('UAH', 'UAH')], max_length=3)),
                ('is_new', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('edit_attempts', models.IntegerField(default=2)),
            ],
            options={
                'db_table': 'cars',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CarProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=60)),
                ('region', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=120)),
                ('owner_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('engine', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electro', 'Electro')], max_length=7)),
                ('engine_capacity', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=9)),
                ('body', models.CharField(choices=[('HatchBack', 'HatchBack'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Wagon', 'Wagon'), ('Jeep', 'Jeep')], max_length=9)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_profiles', to='cars.carmodel')),
            ],
            options={
                'db_table': 'car_profiles',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ModelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cars.brandmodel')),
            ],
            options={
                'db_table': 'models',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='carmodel',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.modelmodel'),
        ),
        migrations.AddConstraint(
            model_name='modelmodel',
            constraint=models.UniqueConstraint(fields=('name', 'brand'), name='unique_model_brand'),
        ),
    ]
