# Generated by Django 5.1 on 2024-09-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carprofileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
