# Generated by Django 5.1 on 2024-09-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carmodel_body_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ('-id',)},
        ),
    ]
