# Generated by Django 5.1 on 2024-09-09 10:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='edit_attempts',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='carprofileview',
            name='body',
            field=models.CharField(choices=[('HatchBack', 'HatchBack'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Wagon', 'Wagon'), ('Jeep', 'Jeep')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='carprofileview',
            name='city',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='carprofileview',
            name='color',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='carprofileview',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carprofileview',
            name='engine',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electro', 'Electro')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='carprofileview',
            name='engine_capacity',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='carprofileview',
            name='mileage',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AddField(
            model_name='carprofileview',
            name='owner_number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='carprofileview',
            name='region',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='carprofileview',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='carprofileview',
            name='car',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_profiles', to='cars.carmodel'),
        ),
    ]
