# Generated by Django 5.1 on 2024-09-09 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_carprofileview_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carprofileview',
            name='body',
            field=models.CharField(choices=[('HatchBack', 'HatchBack'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Wagon', 'Wagon'), ('Jeep', 'Jeep')], max_length=9),
        ),
        migrations.AlterField(
            model_name='carprofileview',
            name='city',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='carprofileview',
            name='color',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='carprofileview',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='carprofileview',
            name='engine',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electro', 'Electro')], max_length=7),
        ),
        migrations.AlterField(
            model_name='carprofileview',
            name='mileage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='carprofileview',
            name='owner_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='carprofileview',
            name='region',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='carprofileview',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=9),
        ),
    ]
