# Generated by Django 5.1 on 2024-09-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermodel_dealership_id_usermodel_is_premium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='dealership_id',
            new_name='dealership',
        ),
    ]
