# Generated by Django 5.1 on 2024-09-10 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profilemodel_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='picture',
            new_name='photo',
        ),
    ]
