# Generated by Django 5.1 on 2024-09-08 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_dealership_id_usermodel_dealership'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='city',
            field=models.CharField(default='Lviv', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
