# Generated by Django 5.1 on 2024-09-10 00:38

from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profilemodel_photo_usermodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='photo',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.services.file_service.FileService.upload_user_photo),
        ),
    ]
