from django.db import models


class RegionChoices(models.TextChoices):
    VOLYN = "Volyn", "Volyn"
    LVIV = "Lviv", "Lviv"
    ZAKARPATIIA = "Zakarpattia", "Zakarpattia"
    RIVNE = "Rivne", "Rivne"
    TERNOPIL = "Ternopil", "Ternopil"
    IVANO_FRANKIVSK = "Ivano-Frankivsk", "Ivano-Frankivsk"
    KHMELNYTSKYI = "Khmelnytskyi", "Khmelnytskyi"
    CHERNIVTSI = "Chernivtsi", "Chernivtsi"
    ZHYTOMYR = "Zhytomyr", "Zhytomyr"
    VINNYTSIA = "Vinnytsia", "Vinnytsia"
    KYIV = "Kyiv", "Kyiv"
    CHERKASY = "Cherkasy", "Cherkasy"
    KIROVOHRAD = "Kirovohrad", "Kirovohrad"
    ODESA = "Odesa", "Odesa"
    MYKOLAIV = "Mykolaiv", "Mykolaiv"
    CHERNIHIV = "Chernihiv", "Chernihiv"
    POLTAVA = "Poltava", "Poltava"
    DNIPROPETROVSK = "Dnipropetrovsk", "Dnipropetrovsk"
    KHERSON = "Kherson", "Kherson"
    ZAPORIZHZHIA = "Zaporizhzhia", "Zaporizhzhia"
    SUMY = "Sumy", "Sumy"
    KHARKIV = "Kharkiv", "Kharkiv"
    DONETSK = "Donetsk", "Donetsk"
    LUHANSK = "Luhansk", "Luhansk"
    KRYM = "Krym", "Krym"
