# Generated by Django 5.1 on 2024-09-10 00:57

from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0003_remove_dealershipmodel_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealershipmodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.services.file_service.FileService.upload_dealership_logo),
        ),
    ]
