# Generated by Django 5.1 on 2024-09-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0005_alter_dealershipmodel_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealershipmodel',
            old_name='admin',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='dealershipmodel',
            name='logo',
        ),
    ]
